# CMake generated Testfile for 
# Source directory: /work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests
# Build directory: /work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(DatabaseReadback.EmptyDatabase "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.EmptyDatabase")
add_test(DatabaseReadback.Book "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Book")
add_test(DatabaseReadback.Clothing "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Clothing")
add_test(DatabaseReadback.Movie "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Movie")
add_test(DatabaseReadback.User "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.User")
add_test(DatabaseReadback.Mixed "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Mixed")
add_test(ConsoleInterface.Quit "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.Quit")
add_test(ConsoleInterface.HitBook "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitBook")
add_test(ConsoleInterface.HitClothing "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitClothing")
add_test(ConsoleInterface.HitMovie "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitMovie")
add_test(ConsoleInterface.CaseInsensitive "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.CaseInsensitive")
add_test(ConsoleInterface.HugeQuantity "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HugeQuantity")
add_test(ConsoleInterface.AddOneToCart "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddOneToCart")
add_test(Database.BuyCart "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCart")
add_test(DatabaseReadback.ThreeBooks "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeBooks")
add_test(DatabaseReadback.ThreeClothes "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeClothes")
add_test(DatabaseReadback.ThreeMovies "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeMovies")
add_test(ConsoleInterface.AddTwoItems "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoItems")
add_test(ConsoleInterface.AddTwoIdenticalItems "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoIdenticalItems")
add_test(Database.BuyCartTwoItems "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCartTwoItems")
add_test(ConsoleInterface.OrMultipleHit "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.OrMultipleHit")
add_test(ConsoleInterface.AndMultipleHit "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AndMultipleHit")
add_test(ConsoleInterface.AddToTwoUsersCarts "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddToTwoUsersCarts")
add_test(ConsoleInterface.AddSameProductTwoUsersCarts "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddSameProductTwoUsersCarts")
add_test(ConsoleInterface.AddTwoProductsTwoUsers "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoProductsTwoUsers")
add_test(Database.BuyTwoProductsTwoUsers "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyTwoProductsTwoUsers")
add_test(ConsoleInterface.BuyCartInsufficientFunds "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.BuyCartInsufficientFunds")
add_test(Database.BuyCartInsufficientFunds "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCartInsufficientFunds")
add_test(ConsoleInterface.AddItemToMultipleUsers "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddItemToMultipleUsers")
add_test(Database.BuySingleStockItemMultipleUsers "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=Database.BuySingleStockItemMultipleUsers")
add_test(ConsoleErrors.ViewCartUnknownUser "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.ViewCartUnknownUser")
add_test(ConsoleErrors.BuyCartUnknownUser "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.BuyCartUnknownUser")
add_test(ConsoleErrors.AddInvalidHitToCart "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.AddInvalidHitToCart")
add_test(AmazonStress.Buy10000Products "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=AmazonStress.Buy10000Products")
add_test(AmazonStress.AndSearch10000Products "/work/csci104/material/artifacts/hw2/grading/amazon/amazon_tests/amazon_tests" "--gtest_filter=AmazonStress.AndSearch10000Products")
